// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WebAPI_MAM;

#nullable disable

namespace WebAPI_MAM.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20230507050624_Inicial")]
    partial class Inicial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0-preview.3.23174.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("WebAPI_MAM.Entities.Appointments", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<int>("DoctorId")
                        .HasColumnType("int");

                    b.Property<int?>("DoctorsId")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("date")
                        .HasColumnType("datetime2");

                    b.Property<int>("diagId")
                        .HasColumnType("int");

                    b.Property<int>("patientId")
                        .HasColumnType("int");

                    b.HasKey("id");

                    b.HasIndex("DoctorsId");

                    b.ToTable("Appointments");
                });

            modelBuilder.Entity("WebAPI_MAM.Entities.Diagnosis", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("Appointmentsid")
                        .HasColumnType("int");

                    b.Property<string>("diagnostic")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("drugs")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("observations")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("treatment")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("Appointmentsid");

                    b.ToTable("Diagnosis");
                });

            modelBuilder.Entity("WebAPI_MAM.Entities.Doctors", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Mail")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("password")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Doctors");
                });

            modelBuilder.Entity("WebAPI_MAM.Entities.MedicInfo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Nss")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("height")
                        .HasColumnType("float");

                    b.Property<string>("sicknessHistory")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("weight")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.ToTable("MedicInfo");
                });

            modelBuilder.Entity("WebAPI_MAM.Entities.Patients", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("appointmentsid")
                        .HasColumnType("int");

                    b.Property<string>("cel")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("mail")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("medicInfoId")
                        .HasColumnType("int");

                    b.Property<string>("name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("password")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("phone")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("appointmentsid");

                    b.HasIndex("medicInfoId");

                    b.ToTable("Patients");
                });

            modelBuilder.Entity("WebAPI_MAM.Entities.Appointments", b =>
                {
                    b.HasOne("WebAPI_MAM.Entities.Doctors", "Doctors")
                        .WithMany("appointments")
                        .HasForeignKey("DoctorsId");

                    b.Navigation("Doctors");
                });

            modelBuilder.Entity("WebAPI_MAM.Entities.Diagnosis", b =>
                {
                    b.HasOne("WebAPI_MAM.Entities.Appointments", null)
                        .WithMany("diagnosis")
                        .HasForeignKey("Appointmentsid");
                });

            modelBuilder.Entity("WebAPI_MAM.Entities.Patients", b =>
                {
                    b.HasOne("WebAPI_MAM.Entities.Appointments", "appointments")
                        .WithMany("patients")
                        .HasForeignKey("appointmentsid");

                    b.HasOne("WebAPI_MAM.Entities.MedicInfo", "medicInfo")
                        .WithMany()
                        .HasForeignKey("medicInfoId");

                    b.Navigation("appointments");

                    b.Navigation("medicInfo");
                });

            modelBuilder.Entity("WebAPI_MAM.Entities.Appointments", b =>
                {
                    b.Navigation("diagnosis");

                    b.Navigation("patients");
                });

            modelBuilder.Entity("WebAPI_MAM.Entities.Doctors", b =>
                {
                    b.Navigation("appointments");
                });
#pragma warning restore 612, 618
        }
    }
}
